#fastlane_version "2.61.0"
#xcversion(version: "9.0.1")

default_platform :ios

lane :alpha do

  cocoapods
  cert
  sigh

  # build settings
  gym(
    scheme: "mclient-alpha",
    export_method: "ad-hoc"
  )

  # upload to HockeyApp
  hockey(
    api_token: "850b28e704a14aa993df89cb7f7020ad",
    release_type: "2",
    notes_type: "1",
    notes: "
Changelog
==================
* Fix: Problem beim laden von Threads am iPad und auf den Plus/Max Phones im Querformat behoben.
"
  )

end

lane :beta do

  cocoapods
  cert
  sigh

  # build settings
  gym(
    scheme: "mclient-beta",
    export_method: "ad-hoc"
  )

  # upload to HockeyApp
  hockey(
    api_token: "850b28e704a14aa993df89cb7f7020ad",
    release_type: "0",
    notes_type: "1",
    notes: "
Changelog
==================
* Fix: Problem beim laden von Threads am iPad und auf den Plus/Max Phones im Querformat behoben.
"
  )

end

lane :beta2 do

  cocoapods
  cert
  sigh

  # build settings
  gym(
    scheme: "mclient",
    export_method: "ad-hoc"
  )

  upload_to_testflight(
    username: "christopher@reitz.re",
    app_identifier: "re.reitz.mclient",
    itc_provider: "J8XDHCNJQA" # pass a specific value to the iTMSTransporter -itc_provider option
  )

  # # upload to HockeyApp
  # hockey(
  #   api_token: "850b28e704a14aa993df89cb7f7020ad",
  #   release_type: "1",
  #   notes_type: "0",
  #   notes: "

  #   "
  # )

end
